# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json
name: Build

concurrency: build

on:
  push:
    branches:
      - master

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - name: Install Nix
        uses: DeterminateSystems/nix-installer-action@main

      - name: Install Magic Nix Cache
        uses: DeterminateSystems/magic-nix-cache-action@main

      - name: Checkout
        uses: actions/checkout@main

      - name: Build
        run: |
          nix build -L
  
      - name: Archive production artifacts
        uses: actions/upload-artifact@v4
        with:
          name: resume
          path: |
             ./result/share/compiled-document/*.pdf
